version: "3.1"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root@db:27017/task-manager?authSource=admin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-volume:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-volume: